[project]
name = "ClockBot"
version = "0.0.0"
authors = [{ name = "WieeRd" }]

# NOTE: I am using pyproject.toml mostly as a config for ruff/pyright
# | dependencies and important stuffs are all specified in the Pipfile


[tool.ruff]
output-format = "grouped"

# FIX: rewrite and bring back legacy cogs written in dpy v1.7
extend-exclude = ["cogs/legacy", "cogs/aprilfools"]

# F403: checks for wildcard imports (`from module import *`)
# F405: checks for undefined names that may be from wildcard imports
# excuse: I will always be using * with `__all__`
per-file-ignores = { "__init__.py" = ["F403", "F405"] }


[tool.pyright]
pythonVersion = "3.11"
ignore = ["cogs/legacy", "cogs/aprilfools"]
