name: Python

on:
  push:
    branches: ["master", "ci-test"]
    paths: ["**/*.py", "Pipfile.lock", "pyproject.toml"]
  pull_request:
    branches: ["master", "ci-test"]
    paths: ["**/*.py", "Pipfile.lock", "pyproject.toml"]

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pipenv
      - name: Install pipenv
        run: PIPENV_VENV_IN_PROJECT=true pipx run pipenv sync
      - name: Activate venv
        run: echo "$PWD/.venv/bin" >> $GITHUB_PATH
      - uses: jakebailey/pyright-action@v1
        with:
          version: 1.1.311

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Ruff linter
        run: pipx run ruff check --output-format github

  format:
    needs: ["pyright", "ruff"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruff
        run: pipx install ruff
      - name: Run isort
        run: ruff check --select I --fix-only
      - name: Run black
        run: ruff format
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: black + isort"
